theme: jekyll-theme-minimal
title: Forecasting With Time Series Models Using R
description: An online textbook that introduces techniques to forecast economic data using time series models with emphasis on coding in R.
