theme: jekyll-theme-minimal
title: Forecasting With Time Series Models Using R
description: A set of materials designed to introduce techniques to forecast economic data using time series models with emphasis on coding in R.
logo: forecasting-logo.png