theme: jekyll-theme-minimal
title: Introduction to Time Series Modeling and Forecasting
description: An online textbook for forecasting methods and practice based on time seried models with emphasis on coding in R.
logo: forecasting-logo.png